import type { Metadata } from "next";
import { AppStorage } from "../data/contexts/globalContext";
import { Inter } from "next/font/google";
import "@fontsource/roboto/300.css";
import "@fontsource/roboto/400.css";
import "@fontsource/roboto/500.css";
import "@fontsource/roboto/700.css";
import "../ui/styles/globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "LEILÃO",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AppStorage>
      <html lang="pt_br">
        <body className={inter.className}>{children}</body>
      </html>
    </AppStorage>
  );
}
